<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Metin2.Shared/Metin2.Shared.csproj" />
    <ProjectReference Include="../Metin2.Protocol.Generator/Metin2.Protocol.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="../../protocol/common/**/*.packet.yml" />
    <AdditionalFiles Include="../../protocol/common/**/*.packet.yaml" />
    <AdditionalFiles Include="../../protocol/client/**/*.packet.yml" />
    <AdditionalFiles Include="../../protocol/client/**/*.packet.yaml" />
    <AdditionalFiles Include="../../protocol/server/**/*.packet.yml" />
    <AdditionalFiles Include="../../protocol/server/**/*.packet.yaml" />
  </ItemGroup>
</Project>
