<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <ProjectReference Include="../Modules/Metin2.Modules.Auth/Metin2.Modules.Auth.csproj" />
    <ProjectReference Include="../Modules/Metin2.Modules.Characters/Metin2.Modules.Characters.csproj" />
    <ProjectReference Include="../Metin2.Shared/Metin2.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
