using System.Text;
using Metin2.Protocol.Generator.Diagnostics;
using Metin2.Protocol.Generator.Generation;
using Metin2.Protocol.Generator.Model;
using Metin2.Protocol.Generator.Parsing;
using Metin2.Protocol.Generator.Validation;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Metin2.Protocol.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class PacketGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<PacketFileResult> packetFiles = context.AdditionalTextsProvider
            .Where(static file =>
                file.Path.EndsWith(".packet.yml", StringComparison.OrdinalIgnoreCase) ||
                file.Path.EndsWith(".packet.yaml", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => ParseFile(file, cancellationToken));

        context.RegisterSourceOutput(packetFiles.Collect(), static (sourceContext, files) =>
        {
            var validDocuments = new List<PacketDocument>();

            foreach (PacketFileResult file in files)
            {
                Location location = CreateFileLocation(file.Path);

                if (file.ParseError is not null)
                {
                    sourceContext.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticCatalog.ParseError,
                        location,
                        file.ParseError));
                    continue;
                }

                if (file.Document is null)
                {
                    continue;
                }

                IReadOnlyList<ValidationFailure> failures = PacketDefinitionValidator.Validate(file.Document);
                foreach (ValidationFailure failure in failures)
                {
                    sourceContext.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticCatalog.ValidationError,
                        location,
                        failure.Code,
                        failure.Message));
                }

                if (failures.Count == 0)
                {
                    validDocuments.Add(file.Document);
                }
            }

            EmitProtocolMetadata(sourceContext, validDocuments);
            EmitPacketModels(sourceContext, validDocuments);
        });
    }

    private static PacketFileResult ParseFile(AdditionalText file, CancellationToken cancellationToken)
    {
        SourceText? sourceText = file.GetText(cancellationToken);
        if (sourceText is null)
        {
            return new PacketFileResult(file.Path, null, "Packet definition file could not be read.");
        }

        try
        {
            var parser = new PacketDefinitionParser();
            PacketDocument document = parser.Parse(sourceText.ToString());
            return new PacketFileResult(file.Path, document, null);
        }
        catch (PacketDefinitionParseException exception)
        {
            return new PacketFileResult(file.Path, null, exception.Message);
        }
    }

    private static Location CreateFileLocation(string path)
    {
        var span = new TextSpan(0, 0);
        var line = new LinePosition(0, 0);
        return Location.Create(path, span, new LinePositionSpan(line, line));
    }

    private static void EmitProtocolMetadata(SourceProductionContext context, IReadOnlyList<PacketDocument> documents)
    {
        int packetCount = documents.Sum(static document => document.Packets.Count);

        string source = $$"""
            // <auto-generated />
            namespace Metin2.Protocol.Generated;

            public enum PacketDirection : byte
            {
                ClientToServer = 1,
                ServerToClient = 2,
                Bidirectional = 3
            }

            public enum PacketPhase : byte
            {
                Any = 0,
                Handshake = 1,
                Auth = 2,
                Select = 3,
                Loading = 4,
                Game = 5
            }

            internal static class ProtocolManifest
            {
                internal const int DefinitionFileCount = {{documents.Count}};
                internal const int PacketCount = {{packetCount}};
            }
            """;

        context.AddSource("ProtocolMetadata.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static void EmitPacketModels(SourceProductionContext context, IReadOnlyList<PacketDocument> documents)
    {
        foreach (PacketDefinition packet in documents.SelectMany(static document => document.Packets))
        {
            string source = PacketModelEmitter.Emit(packet);
            context.AddSource($"Packets.{packet.Name}.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private sealed class PacketFileResult
    {
        public PacketFileResult(string path, PacketDocument? document, string? parseError)
        {
            Path = path;
            Document = document;
            ParseError = parseError;
        }

        public string Path { get; }
        public PacketDocument? Document { get; }
        public string? ParseError { get; }
    }
}
