CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    username_normalized VARCHAR(30) NOT NULL,
    password_hash TEXT NOT NULL,
    login_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_accounts_id_uint32 CHECK (id BETWEEN 1 AND 4294967295),
    CONSTRAINT uq_accounts_username_normalized UNIQUE (username_normalized)
);

CREATE INDEX IF NOT EXISTS ix_accounts_login_enabled
    ON accounts (login_enabled);
