ALTER TABLE accounts
    ADD COLUMN empire SMALLINT NOT NULL DEFAULT 0 CHECK (empire BETWEEN 0 AND 3);

CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    slot SMALLINT NOT NULL,
    name VARCHAR(24) NOT NULL,
    class SMALLINT NOT NULL DEFAULT 0,
    level SMALLINT NOT NULL DEFAULT 1,
    playtime_minutes BIGINT NOT NULL DEFAULT 0,
    strength SMALLINT NOT NULL DEFAULT 0,
    vitality SMALLINT NOT NULL DEFAULT 0,
    dexterity SMALLINT NOT NULL DEFAULT 0,
    intelligence SMALLINT NOT NULL DEFAULT 0,
    body_part INTEGER NOT NULL DEFAULT 0,
    name_change SMALLINT NOT NULL DEFAULT 0,
    hair_part INTEGER NOT NULL DEFAULT 0,
    position_x INTEGER NOT NULL DEFAULT 0,
    position_y INTEGER NOT NULL DEFAULT 0,
    map_id INTEGER NOT NULL DEFAULT 1,
    skill_group SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_characters_id_uint32 CHECK (id BETWEEN 1 AND 4294967295),
    CONSTRAINT ck_characters_slot CHECK (slot BETWEEN 0 AND 3),
    CONSTRAINT ck_characters_class_u8 CHECK (class BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_level_u8 CHECK (level BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_playtime_uint32 CHECK (playtime_minutes BETWEEN 0 AND 4294967295),
    CONSTRAINT ck_characters_strength_u8 CHECK (strength BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_vitality_u8 CHECK (vitality BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_dexterity_u8 CHECK (dexterity BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_intelligence_u8 CHECK (intelligence BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_body_part_u16 CHECK (body_part BETWEEN 0 AND 65535),
    CONSTRAINT ck_characters_name_change_u8 CHECK (name_change BETWEEN 0 AND 255),
    CONSTRAINT ck_characters_hair_part_u16 CHECK (hair_part BETWEEN 0 AND 65535),
    CONSTRAINT ck_characters_skill_group_u8 CHECK (skill_group BETWEEN 0 AND 255),
    CONSTRAINT uq_characters_account_slot UNIQUE (account_id, slot),
    CONSTRAINT uq_characters_name UNIQUE (name)
);

CREATE INDEX ix_characters_account_id
    ON characters (account_id);
