using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class FixedPacketCodecEmitter
{
    private const string GeneratedNamespace = "Metin2.Protocol.Generated.Packets";

    public static bool CanEmit(PacketDefinition packet) =>
        packet.Size == "fixed" && packet.Fields.All(static field => TryGetWireInfo(field.Type, out _, out _, out _));

    public static string Emit(PacketDefinition packet)
    {
        int payloadSize = packet.Fields.Sum(static field =>
        {
            _ = TryGetWireInfo(field.Type, out int size, out _, out _);
            return size;
        });

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();
        source.AppendLine($"public static class {packet.Name}Codec");
        source.AppendLine("{");
        source.AppendLine($"    public const int PayloadSize = {payloadSize};");
        source.AppendLine();
        EmitReader(source, packet);
        source.AppendLine();
        EmitWriter(source, packet);
        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitReader(StringBuilder source, PacketDefinition packet)
    {
        source.AppendLine($"    public static bool TryRead(ref global::Metin2.Protocol.IO.PacketReader reader, out {packet.Name} packet)");
        source.AppendLine("    {");
        source.AppendLine("        packet = default;");
        source.AppendLine("        if (reader.Remaining < PayloadSize)");
        source.AppendLine("        {");
        source.AppendLine("            return false;");
        source.AppendLine("        }");
        source.AppendLine();

        foreach (FieldDefinition field in packet.Fields)
        {
            _ = TryGetWireInfo(field.Type, out _, out string rawType, out string readMethod);
            string localName = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));
            source.AppendLine($"        if (!reader.{readMethod}(out {rawType} {localName}Raw))");
            source.AppendLine("        {");
            source.AppendLine("            return false;");
            source.AppendLine("        }");
        }

        if (packet.Fields.Count > 0)
        {
            source.AppendLine();
        }

        string arguments = string.Join(",\n            ", packet.Fields.Select(BuildReadArgument));
        if (packet.Fields.Count == 0)
        {
            source.AppendLine($"        packet = new {packet.Name}();");
        }
        else
        {
            source.AppendLine($"        packet = new {packet.Name}(\n            {arguments});");
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static void EmitWriter(StringBuilder source, PacketDefinition packet)
    {
        source.AppendLine($"    public static bool TryWrite(ref global::Metin2.Protocol.IO.PacketWriter writer, in {packet.Name} packet)");
        source.AppendLine("    {");
        source.AppendLine("        if (writer.Remaining < PayloadSize)");
        source.AppendLine("        {");
        source.AppendLine("            return false;");
        source.AppendLine("        }");

        if (packet.Fields.Count == 0)
        {
            source.AppendLine();
            source.AppendLine("        return true;");
            source.AppendLine("    }");
            return;
        }

        source.AppendLine();
        for (int index = 0; index < packet.Fields.Count; index++)
        {
            FieldDefinition field = packet.Fields[index];
            _ = TryGetWireInfo(field.Type, out _, out _, out string readMethod);
            string writeMethod = readMethod.Replace("TryRead", "TryWrite");
            string propertyName = PacketModelEmitter.ToPascalCase(field.Name);
            string value = string.IsNullOrWhiteSpace(field.DomainType)
                ? $"packet.{propertyName}"
                : $"packet.{propertyName}.Value";

            string suffix = index == packet.Fields.Count - 1 ? ";" : " &&";
            source.AppendLine(index == 0
                ? $"        return writer.{writeMethod}({value}){suffix}"
                : $"            writer.{writeMethod}({value}){suffix}");
        }

        source.AppendLine("    }");
    }

    private static string BuildReadArgument(FieldDefinition field)
    {
        string localName = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));
        if (string.IsNullOrWhiteSpace(field.DomainType))
        {
            return $"{localName}Raw";
        }

        string domainType = field.DomainType switch
        {
            "AccountId" => "global::Metin2.Shared.Identity.AccountId",
            "CharacterId" => "global::Metin2.Shared.Identity.CharacterId",
            "ItemId" => "global::Metin2.Shared.Identity.ItemId",
            "GuildId" => "global::Metin2.Shared.Identity.GuildId",
            "MapId" => "global::Metin2.Shared.Identity.MapId",
            "EntityId" => "global::Metin2.Shared.Identity.EntityId",
            "MonsterId" => "global::Metin2.Shared.Identity.MonsterId",
            _ => field.DomainType!
        };

        return $"new {domainType}({localName}Raw)";
    }

    private static bool TryGetWireInfo(string type, out int size, out string rawType, out string readMethod)
    {
        switch (type)
        {
            case "i8": size = 1; rawType = "sbyte"; readMethod = "TryReadSByte"; return true;
            case "u8": size = 1; rawType = "byte"; readMethod = "TryReadByte"; return true;
            case "i16le": size = 2; rawType = "short"; readMethod = "TryReadInt16LittleEndian"; return true;
            case "i16be": size = 2; rawType = "short"; readMethod = "TryReadInt16BigEndian"; return true;
            case "u16le": size = 2; rawType = "ushort"; readMethod = "TryReadUInt16LittleEndian"; return true;
            case "u16be": size = 2; rawType = "ushort"; readMethod = "TryReadUInt16BigEndian"; return true;
            case "i32le": size = 4; rawType = "int"; readMethod = "TryReadInt32LittleEndian"; return true;
            case "i32be": size = 4; rawType = "int"; readMethod = "TryReadInt32BigEndian"; return true;
            case "u32le": size = 4; rawType = "uint"; readMethod = "TryReadUInt32LittleEndian"; return true;
            case "u32be": size = 4; rawType = "uint"; readMethod = "TryReadUInt32BigEndian"; return true;
            case "i64le": size = 8; rawType = "long"; readMethod = "TryReadInt64LittleEndian"; return true;
            case "i64be": size = 8; rawType = "long"; readMethod = "TryReadInt64BigEndian"; return true;
            case "u64le": size = 8; rawType = "ulong"; readMethod = "TryReadUInt64LittleEndian"; return true;
            case "u64be": size = 8; rawType = "ulong"; readMethod = "TryReadUInt64BigEndian"; return true;
            case "f32le": size = 4; rawType = "float"; readMethod = "TryReadSingleLittleEndian"; return true;
            case "f32be": size = 4; rawType = "float"; readMethod = "TryReadSingleBigEndian"; return true;
            case "f64le": size = 8; rawType = "double"; readMethod = "TryReadDoubleLittleEndian"; return true;
            case "f64be": size = 8; rawType = "double"; readMethod = "TryReadDoubleBigEndian"; return true;
            case "bool8": size = 1; rawType = "bool"; readMethod = "TryReadBool8"; return true;
            default:
                size = 0;
                rawType = string.Empty;
                readMethod = string.Empty;
                return false;
        }
    }

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);
}
