using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class FixedWireTypeEmitter
{
    private const string GeneratedNamespace = "Metin2.Protocol.Generated.Types";

    public static bool CanEmit(WireTypeDefinition type) =>
        type.Size == "fixed" && type.Fields.All(CanEmitField);

    public static int GetPayloadSize(WireTypeDefinition type) =>
        type.Fields.Sum(GetFieldSize);

    public static string Emit(WireTypeDefinition type)
    {
        int payloadSize = GetPayloadSize(type);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();

        if (type.Fields.Count == 0)
        {
            source.AppendLine($"public readonly record struct {type.Name};");
        }
        else
        {
            string parameters = string.Join(",\n    ", type.Fields.Select(field =>
                $"{PacketModelEmitter.MapFieldType(field)} {PacketModelEmitter.GetMemberName(type.Name, field)}"));
            source.AppendLine($"public readonly record struct {type.Name}(\n    {parameters});");
        }

        source.AppendLine();
        source.AppendLine($"public static class {type.Name}Codec");
        source.AppendLine("{");
        source.AppendLine($"    public const int PayloadSize = {payloadSize};");
        source.AppendLine();
        EmitReader(source, type);
        source.AppendLine();
        EmitWriter(source, type);
        source.AppendLine("}");
        return source.ToString();
    }

    private static bool CanEmitField(FieldDefinition field) =>
        TryGetScalarWireInfo(field.Type, out _, out _, out _) ||
        (field.Type == "fixed_string" && field.Length is > 0 && field.Encoding == "ascii" && field.Termination == "null");

    private static int GetFieldSize(FieldDefinition field)
    {
        if (TryGetScalarWireInfo(field.Type, out int size, out _, out _)) return size;
        if (field.Type == "fixed_string") return field.Length!.Value;
        throw new InvalidOperationException($"Unsupported fixed composite field '{field.Name}' of type '{field.Type}'.");
    }

    private static void EmitReader(StringBuilder source, WireTypeDefinition type)
    {
        source.AppendLine($"    public static bool TryRead(ref global::Metin2.Protocol.IO.PacketReader reader, out {type.Name} value)");
        source.AppendLine("    {");
        source.AppendLine("        value = default;");
        source.AppendLine("        if (reader.Remaining < PayloadSize) return false;");

        foreach (FieldDefinition field in type.Fields)
        {
            string local = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));
            if (TryGetScalarWireInfo(field.Type, out _, out string rawType, out string readMethod))
            {
                source.AppendLine($"        if (!reader.{readMethod}(out {rawType} {local}Raw)) return false;");
            }
            else
            {
                source.AppendLine($"        if (!reader.TryReadFixedAsciiNullTerminated({field.Length!.Value}, out string {local}Raw)) return false;");
            }
        }

        if (type.Fields.Count == 0)
        {
            source.AppendLine($"        value = new {type.Name}();");
        }
        else
        {
            string args = string.Join(",\n            ", type.Fields.Select(BuildReadArgument));
            source.AppendLine($"        value = new {type.Name}(\n            {args});");
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static void EmitWriter(StringBuilder source, WireTypeDefinition type)
    {
        source.AppendLine($"    public static bool TryWrite(ref global::Metin2.Protocol.IO.PacketWriter writer, in {type.Name} value)");
        source.AppendLine("    {");
        source.AppendLine("        if (writer.Remaining < PayloadSize) return false;");

        foreach (FieldDefinition field in type.Fields.Where(static field => field.Type == "fixed_string"))
        {
            string member = PacketModelEmitter.GetMemberName(type.Name, field);
            source.AppendLine($"        if (global::System.Text.Encoding.ASCII.GetByteCount(value.{member} ?? string.Empty) > {field.Length!.Value - 1}) return false;");
        }

        foreach (FieldDefinition field in type.Fields)
        {
            string member = PacketModelEmitter.GetMemberName(type.Name, field);
            if (TryGetScalarWireInfo(field.Type, out _, out _, out string readMethod))
            {
                string writeMethod = readMethod.Replace("TryRead", "TryWrite");
                string fieldValue = string.IsNullOrWhiteSpace(field.DomainType)
                    ? $"value.{member}"
                    : $"value.{member}.Value";
                source.AppendLine($"        if (!writer.{writeMethod}({fieldValue})) return false;");
            }
            else
            {
                source.AppendLine($"        if (!writer.TryWriteFixedAsciiNullTerminated(value.{member}, {field.Length!.Value})) return false;");
            }
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static string BuildReadArgument(FieldDefinition field)
    {
        string local = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));
        if (field.Type == "fixed_string" || string.IsNullOrWhiteSpace(field.DomainType)) return $"{local}Raw";
        return $"new {PacketModelEmitter.MapDomainType(field.DomainType!)}({local}Raw)";
    }

    internal static bool TryGetScalarWireInfo(string type, out int size, out string rawType, out string readMethod)
    {
        switch (type)
        {
            case "i8": size = 1; rawType = "sbyte"; readMethod = "TryReadSByte"; return true;
            case "u8": size = 1; rawType = "byte"; readMethod = "TryReadByte"; return true;
            case "i16le": size = 2; rawType = "short"; readMethod = "TryReadInt16LittleEndian"; return true;
            case "i16be": size = 2; rawType = "short"; readMethod = "TryReadInt16BigEndian"; return true;
            case "u16le": size = 2; rawType = "ushort"; readMethod = "TryReadUInt16LittleEndian"; return true;
            case "u16be": size = 2; rawType = "ushort"; readMethod = "TryReadUInt16BigEndian"; return true;
            case "i32le": size = 4; rawType = "int"; readMethod = "TryReadInt32LittleEndian"; return true;
            case "i32be": size = 4; rawType = "int"; readMethod = "TryReadInt32BigEndian"; return true;
            case "u32le": size = 4; rawType = "uint"; readMethod = "TryReadUInt32LittleEndian"; return true;
            case "u32be": size = 4; rawType = "uint"; readMethod = "TryReadUInt32BigEndian"; return true;
            case "i64le": size = 8; rawType = "long"; readMethod = "TryReadInt64LittleEndian"; return true;
            case "i64be": size = 8; rawType = "long"; readMethod = "TryReadInt64BigEndian"; return true;
            case "u64le": size = 8; rawType = "ulong"; readMethod = "TryReadUInt64LittleEndian"; return true;
            case "u64be": size = 8; rawType = "ulong"; readMethod = "TryReadUInt64BigEndian"; return true;
            case "f32le": size = 4; rawType = "float"; readMethod = "TryReadSingleLittleEndian"; return true;
            case "f32be": size = 4; rawType = "float"; readMethod = "TryReadSingleBigEndian"; return true;
            case "f64le": size = 8; rawType = "double"; readMethod = "TryReadDoubleLittleEndian"; return true;
            case "f64be": size = 8; rawType = "double"; readMethod = "TryReadDoubleBigEndian"; return true;
            case "bool8": size = 1; rawType = "bool"; readMethod = "TryReadBool8"; return true;
            default:
                size = 0;
                rawType = string.Empty;
                readMethod = string.Empty;
                return false;
        }
    }

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);
}
