using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class FixedPacketCodecEmitter
{
    private const string GeneratedNamespace = "Metin2.Protocol.Generated.Packets";

    public static bool CanEmit(PacketDefinition packet, IReadOnlyDictionary<string, WireTypeDefinition> wireTypes) =>
        packet.Size == "fixed" && packet.Fields.All(field => CanEmitField(field, wireTypes));

    public static string Emit(PacketDefinition packet, IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        int payloadSize = packet.Fields.Sum(field => GetFieldSize(field, wireTypes));

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();
        source.AppendLine($"public static class {packet.Name}Codec");
        source.AppendLine("{");
        source.AppendLine($"    public const int PayloadSize = {payloadSize};");
        source.AppendLine();
        EmitReader(source, packet, wireTypes);
        source.AppendLine();
        EmitWriter(source, packet, wireTypes);
        source.AppendLine("}");
        return source.ToString();
    }

    private static bool CanEmitField(FieldDefinition field, IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        if (FixedWireTypeEmitter.TryGetScalarWireInfo(field.Type, out _, out _, out _)) return true;
        if (IsSupportedFixedString(field.Length, field.Encoding, field.Termination)) return true;
        if (wireTypes.ContainsKey(field.Type)) return true;

        if (field.Type == "array" && field.Length is > 0 && field.Element is not null)
        {
            ElementDefinition element = field.Element;
            return FixedWireTypeEmitter.TryGetScalarWireInfo(element.Type, out _, out _, out _) ||
                   IsSupportedFixedString(element.Length, element.Encoding, element.Termination) ||
                   wireTypes.ContainsKey(element.Type);
        }

        return false;
    }

    private static bool IsSupportedFixedString(int? length, string? encoding, string? termination) =>
        length is > 0 && encoding == "ascii" && termination == "null";

    private static int GetFieldSize(FieldDefinition field, IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        if (FixedWireTypeEmitter.TryGetScalarWireInfo(field.Type, out int scalarSize, out _, out _)) return scalarSize;
        if (field.Type == "fixed_string") return field.Length!.Value;
        if (wireTypes.TryGetValue(field.Type, out WireTypeDefinition? composite))
            return FixedWireTypeEmitter.GetPayloadSize(composite);

        if (field.Type == "array")
        {
            ElementDefinition element = field.Element!;
            int elementSize;
            if (FixedWireTypeEmitter.TryGetScalarWireInfo(element.Type, out elementSize, out _, out _))
            {
            }
            else if (element.Type == "fixed_string")
            {
                elementSize = element.Length!.Value;
            }
            else if (wireTypes.TryGetValue(element.Type, out WireTypeDefinition? elementComposite))
            {
                elementSize = FixedWireTypeEmitter.GetPayloadSize(elementComposite);
            }
            else
            {
                throw new InvalidOperationException($"Unsupported array element '{element.Type}'.");
            }

            return checked(field.Length!.Value * elementSize);
        }

        throw new InvalidOperationException($"Unsupported fixed field '{field.Name}' of type '{field.Type}'.");
    }

    private static void EmitReader(
        StringBuilder source,
        PacketDefinition packet,
        IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        source.AppendLine($"    public static bool TryRead(ref global::Metin2.Protocol.IO.PacketReader reader, out {packet.Name} packet)");
        source.AppendLine("    {");
        source.AppendLine("        packet = default;");
        source.AppendLine("        if (reader.Remaining < PayloadSize) return false;");
        source.AppendLine();

        foreach (FieldDefinition field in packet.Fields)
        {
            EmitFieldRead(source, field, wireTypes);
        }

        if (packet.Fields.Count > 0) source.AppendLine();

        if (packet.Fields.Count == 0)
        {
            source.AppendLine($"        packet = new {packet.Name}();");
        }
        else
        {
            string arguments = string.Join(",\n            ", packet.Fields.Select(BuildReadArgument));
            source.AppendLine($"        packet = new {packet.Name}(\n            {arguments});");
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static void EmitFieldRead(
        StringBuilder source,
        FieldDefinition field,
        IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        string localName = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));

        if (FixedWireTypeEmitter.TryGetScalarWireInfo(field.Type, out _, out string rawType, out string readMethod))
        {
            source.AppendLine($"        if (!reader.{readMethod}(out {rawType} {localName}Raw)) return false;");
            return;
        }

        if (field.Type == "fixed_string")
        {
            source.AppendLine($"        if (!reader.TryReadFixedAsciiNullTerminated({field.Length!.Value}, out string {localName}Raw)) return false;");
            return;
        }

        if (wireTypes.ContainsKey(field.Type))
        {
            string typeName = PacketModelEmitter.MapWireType(field.Type);
            source.AppendLine($"        if (!global::Metin2.Protocol.Generated.Types.{field.Type}Codec.TryRead(ref reader, out {typeName} {localName}Raw)) return false;");
            return;
        }

        ElementDefinition element = field.Element!;
        string elementModelType = PacketModelEmitter.MapWireOrDomainType(element.Type, element.DomainType);
        source.AppendLine($"        var {localName}Raw = new {elementModelType}[{field.Length!.Value}];");
        source.AppendLine($"        for (int i = 0; i < {localName}Raw.Length; i++)");
        source.AppendLine("        {");

        if (FixedWireTypeEmitter.TryGetScalarWireInfo(element.Type, out _, out string elementRawType, out string elementReadMethod))
        {
            source.AppendLine($"            if (!reader.{elementReadMethod}(out {elementRawType} itemRaw)) return false;");
            source.AppendLine(string.IsNullOrWhiteSpace(element.DomainType)
                ? $"            {localName}Raw[i] = itemRaw;"
                : $"            {localName}Raw[i] = new {PacketModelEmitter.MapDomainType(element.DomainType!)}(itemRaw);");
        }
        else if (element.Type == "fixed_string")
        {
            source.AppendLine($"            if (!reader.TryReadFixedAsciiNullTerminated({element.Length!.Value}, out string itemRaw)) return false;");
            source.AppendLine($"            {localName}Raw[i] = itemRaw;");
        }
        else
        {
            source.AppendLine($"            if (!global::Metin2.Protocol.Generated.Types.{element.Type}Codec.TryRead(ref reader, out {elementModelType} itemRaw)) return false;");
            source.AppendLine($"            {localName}Raw[i] = itemRaw;");
        }

        source.AppendLine("        }");
    }

    private static void EmitWriter(
        StringBuilder source,
        PacketDefinition packet,
        IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        source.AppendLine($"    public static bool TryWrite(ref global::Metin2.Protocol.IO.PacketWriter writer, in {packet.Name} packet)");
        source.AppendLine("    {");
        source.AppendLine("        if (writer.Remaining < PayloadSize) return false;");

        foreach (FieldDefinition field in packet.Fields)
        {
            string propertyName = PacketModelEmitter.GetMemberName(packet, field);
            if (field.Type == "fixed_string")
            {
                source.AppendLine($"        if (global::System.Text.Encoding.ASCII.GetByteCount(packet.{propertyName} ?? string.Empty) > {field.Length!.Value - 1}) return false;");
            }
            else if (field.Type == "array")
            {
                source.AppendLine($"        if (packet.{propertyName}.Length != {field.Length!.Value}) return false;");
                if (field.Element!.Type == "fixed_string")
                {
                    string spanName = ToCamelCase(propertyName) + "ValidationSpan";
                    source.AppendLine($"        global::System.ReadOnlySpan<string> {spanName} = packet.{propertyName}.Span;");
                    source.AppendLine($"        for (int i = 0; i < {spanName}.Length; i++)");
                    source.AppendLine("        {");
                    source.AppendLine($"            if (global::System.Text.Encoding.ASCII.GetByteCount({spanName}[i] ?? string.Empty) > {field.Element.Length!.Value - 1}) return false;");
                    source.AppendLine("        }");
                }
            }
        }

        if (packet.Fields.Count > 0) source.AppendLine();

        foreach (FieldDefinition field in packet.Fields)
        {
            EmitFieldWrite(source, packet, field, wireTypes);
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static void EmitFieldWrite(
        StringBuilder source,
        PacketDefinition packet,
        FieldDefinition field,
        IReadOnlyDictionary<string, WireTypeDefinition> wireTypes)
    {
        string propertyName = PacketModelEmitter.GetMemberName(packet, field);

        if (FixedWireTypeEmitter.TryGetScalarWireInfo(field.Type, out _, out _, out string readMethod))
        {
            string writeMethod = readMethod.Replace("TryRead", "TryWrite");
            string value = string.IsNullOrWhiteSpace(field.DomainType)
                ? $"packet.{propertyName}"
                : $"packet.{propertyName}.Value";
            source.AppendLine($"        if (!writer.{writeMethod}({value})) return false;");
            return;
        }

        if (field.Type == "fixed_string")
        {
            source.AppendLine($"        if (!writer.TryWriteFixedAsciiNullTerminated(packet.{propertyName}, {field.Length!.Value})) return false;");
            return;
        }

        if (wireTypes.ContainsKey(field.Type))
        {
            source.AppendLine($"        if (!global::Metin2.Protocol.Generated.Types.{field.Type}Codec.TryWrite(ref writer, in packet.{propertyName})) return false;");
            return;
        }

        ElementDefinition element = field.Element!;
        string elementModelType = PacketModelEmitter.MapWireOrDomainType(element.Type, element.DomainType);
        string spanName = ToCamelCase(propertyName) + "Span";
        source.AppendLine($"        global::System.ReadOnlySpan<{elementModelType}> {spanName} = packet.{propertyName}.Span;");
        source.AppendLine($"        for (int i = 0; i < {spanName}.Length; i++)");
        source.AppendLine("        {");

        if (FixedWireTypeEmitter.TryGetScalarWireInfo(element.Type, out _, out _, out string elementReadMethod))
        {
            string elementWriteMethod = elementReadMethod.Replace("TryRead", "TryWrite");
            string elementValue = string.IsNullOrWhiteSpace(element.DomainType)
                ? $"{spanName}[i]"
                : $"{spanName}[i].Value";
            source.AppendLine($"            if (!writer.{elementWriteMethod}({elementValue})) return false;");
        }
        else if (element.Type == "fixed_string")
        {
            source.AppendLine($"            if (!writer.TryWriteFixedAsciiNullTerminated({spanName}[i], {element.Length!.Value})) return false;");
        }
        else
        {
            source.AppendLine($"            {elementModelType} item = {spanName}[i];");
            source.AppendLine($"            if (!global::Metin2.Protocol.Generated.Types.{element.Type}Codec.TryWrite(ref writer, in item)) return false;");
        }

        source.AppendLine("        }");
    }

    private static string BuildReadArgument(FieldDefinition field)
    {
        string localName = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));

        if (field.Type is "fixed_string" or "array") return $"{localName}Raw";
        if (string.IsNullOrWhiteSpace(field.DomainType)) return $"{localName}Raw";

        return $"new {PacketModelEmitter.MapDomainType(field.DomainType!)}({localName}Raw)";
    }

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);
}
