using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class FixedPacketCodecEmitter
{
    private const string GeneratedNamespace = "Metin2.Protocol.Generated.Packets";

    public static bool CanEmit(PacketDefinition packet) =>
        packet.Size == "fixed" && packet.Fields.All(CanEmitField);

    public static string Emit(PacketDefinition packet)
    {
        int payloadSize = packet.Fields.Sum(GetFieldSize);

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();
        source.AppendLine($"public static class {packet.Name}Codec");
        source.AppendLine("{");
        source.AppendLine($"    public const int PayloadSize = {payloadSize};");
        source.AppendLine();
        EmitReader(source, packet);
        source.AppendLine();
        EmitWriter(source, packet);
        source.AppendLine("}");
        return source.ToString();
    }

    private static bool CanEmitField(FieldDefinition field)
    {
        if (TryGetScalarWireInfo(field.Type, out _, out _, out _)) return true;

        if (field.Type == "fixed_string")
        {
            return field.Length is > 0 &&
                   field.Encoding == "ascii" &&
                   field.Termination == "null";
        }

        if (field.Type == "array")
        {
            return field.Length is > 0 &&
                   field.Element is not null &&
                   TryGetScalarWireInfo(field.Element.Type, out _, out _, out _);
        }

        return false;
    }

    private static int GetFieldSize(FieldDefinition field)
    {
        if (TryGetScalarWireInfo(field.Type, out int scalarSize, out _, out _)) return scalarSize;
        if (field.Type == "fixed_string") return field.Length!.Value;
        if (field.Type == "array")
        {
            _ = TryGetScalarWireInfo(field.Element!.Type, out int elementSize, out _, out _);
            return checked(field.Length!.Value * elementSize);
        }

        throw new InvalidOperationException($"Unsupported fixed field '{field.Name}' of type '{field.Type}'.");
    }

    private static void EmitReader(StringBuilder source, PacketDefinition packet)
    {
        source.AppendLine($"    public static bool TryRead(ref global::Metin2.Protocol.IO.PacketReader reader, out {packet.Name} packet)");
        source.AppendLine("    {");
        source.AppendLine("        packet = default;");
        source.AppendLine("        if (reader.Remaining < PayloadSize)");
        source.AppendLine("        {");
        source.AppendLine("            return false;");
        source.AppendLine("        }");
        source.AppendLine();

        foreach (FieldDefinition field in packet.Fields)
        {
            EmitFieldRead(source, field);
        }

        if (packet.Fields.Count > 0) source.AppendLine();

        if (packet.Fields.Count == 0)
        {
            source.AppendLine($"        packet = new {packet.Name}();");
        }
        else
        {
            string arguments = string.Join(",\n            ", packet.Fields.Select(BuildReadArgument));
            source.AppendLine($"        packet = new {packet.Name}(\n            {arguments});");
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static void EmitFieldRead(StringBuilder source, FieldDefinition field)
    {
        string localName = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));

        if (TryGetScalarWireInfo(field.Type, out _, out string rawType, out string readMethod))
        {
            source.AppendLine($"        if (!reader.{readMethod}(out {rawType} {localName}Raw)) return false;");
            return;
        }

        if (field.Type == "fixed_string")
        {
            source.AppendLine($"        if (!reader.TryReadFixedAsciiNullTerminated({field.Length!.Value}, out string {localName}Raw)) return false;");
            return;
        }

        ElementDefinition element = field.Element!;
        _ = TryGetScalarWireInfo(element.Type, out _, out string elementRawType, out string elementReadMethod);
        string elementModelType = PacketModelEmitter.MapWireOrDomainType(element.Type, element.DomainType);
        source.AppendLine($"        var {localName}Raw = new {elementModelType}[{field.Length!.Value}];");
        source.AppendLine($"        for (int i = 0; i < {localName}Raw.Length; i++)");
        source.AppendLine("        {");
        source.AppendLine($"            if (!reader.{elementReadMethod}(out {elementRawType} itemRaw)) return false;");
        source.AppendLine(string.IsNullOrWhiteSpace(element.DomainType)
            ? $"            {localName}Raw[i] = itemRaw;"
            : $"            {localName}Raw[i] = new {PacketModelEmitter.MapDomainType(element.DomainType!)}(itemRaw);");
        source.AppendLine("        }");
    }

    private static void EmitWriter(StringBuilder source, PacketDefinition packet)
    {
        source.AppendLine($"    public static bool TryWrite(ref global::Metin2.Protocol.IO.PacketWriter writer, in {packet.Name} packet)");
        source.AppendLine("    {");
        source.AppendLine("        if (writer.Remaining < PayloadSize) return false;");

        foreach (FieldDefinition field in packet.Fields)
        {
            string propertyName = PacketModelEmitter.GetMemberName(packet, field);
            if (field.Type == "fixed_string")
            {
                source.AppendLine($"        if (global::System.Text.Encoding.ASCII.GetByteCount(packet.{propertyName} ?? string.Empty) > {field.Length!.Value - 1}) return false;");
            }
            else if (field.Type == "array")
            {
                source.AppendLine($"        if (packet.{propertyName}.Length != {field.Length!.Value}) return false;");
            }
        }

        if (packet.Fields.Count > 0) source.AppendLine();

        foreach (FieldDefinition field in packet.Fields)
        {
            EmitFieldWrite(source, packet, field);
        }

        source.AppendLine("        return true;");
        source.AppendLine("    }");
    }

    private static void EmitFieldWrite(StringBuilder source, PacketDefinition packet, FieldDefinition field)
    {
        string propertyName = PacketModelEmitter.GetMemberName(packet, field);

        if (TryGetScalarWireInfo(field.Type, out _, out _, out string readMethod))
        {
            string writeMethod = readMethod.Replace("TryRead", "TryWrite");
            string value = string.IsNullOrWhiteSpace(field.DomainType)
                ? $"packet.{propertyName}"
                : $"packet.{propertyName}.Value";
            source.AppendLine($"        if (!writer.{writeMethod}({value})) return false;");
            return;
        }

        if (field.Type == "fixed_string")
        {
            source.AppendLine($"        if (!writer.TryWriteFixedAsciiNullTerminated(packet.{propertyName}, {field.Length!.Value})) return false;");
            return;
        }

        ElementDefinition element = field.Element!;
        _ = TryGetScalarWireInfo(element.Type, out _, out _, out string elementReadMethod);
        string elementWriteMethod = elementReadMethod.Replace("TryRead", "TryWrite");
        string spanName = ToCamelCase(propertyName) + "Span";
        source.AppendLine($"        global::System.ReadOnlySpan<{PacketModelEmitter.MapWireOrDomainType(element.Type, element.DomainType)}> {spanName} = packet.{propertyName}.Span;");
        source.AppendLine($"        for (int i = 0; i < {spanName}.Length; i++)");
        source.AppendLine("        {");
        string elementValue = string.IsNullOrWhiteSpace(element.DomainType)
            ? $"{spanName}[i]"
            : $"{spanName}[i].Value";
        source.AppendLine($"            if (!writer.{elementWriteMethod}({elementValue})) return false;");
        source.AppendLine("        }");
    }

    private static string BuildReadArgument(FieldDefinition field)
    {
        string localName = ToCamelCase(PacketModelEmitter.ToPascalCase(field.Name));

        if (field.Type is "fixed_string" or "array") return $"{localName}Raw";
        if (string.IsNullOrWhiteSpace(field.DomainType)) return $"{localName}Raw";

        return $"new {PacketModelEmitter.MapDomainType(field.DomainType!)}({localName}Raw)";
    }

    private static bool TryGetScalarWireInfo(string type, out int size, out string rawType, out string readMethod)
    {
        switch (type)
        {
            case "i8": size = 1; rawType = "sbyte"; readMethod = "TryReadSByte"; return true;
            case "u8": size = 1; rawType = "byte"; readMethod = "TryReadByte"; return true;
            case "i16le": size = 2; rawType = "short"; readMethod = "TryReadInt16LittleEndian"; return true;
            case "i16be": size = 2; rawType = "short"; readMethod = "TryReadInt16BigEndian"; return true;
            case "u16le": size = 2; rawType = "ushort"; readMethod = "TryReadUInt16LittleEndian"; return true;
            case "u16be": size = 2; rawType = "ushort"; readMethod = "TryReadUInt16BigEndian"; return true;
            case "i32le": size = 4; rawType = "int"; readMethod = "TryReadInt32LittleEndian"; return true;
            case "i32be": size = 4; rawType = "int"; readMethod = "TryReadInt32BigEndian"; return true;
            case "u32le": size = 4; rawType = "uint"; readMethod = "TryReadUInt32LittleEndian"; return true;
            case "u32be": size = 4; rawType = "uint"; readMethod = "TryReadUInt32BigEndian"; return true;
            case "i64le": size = 8; rawType = "long"; readMethod = "TryReadInt64LittleEndian"; return true;
            case "i64be": size = 8; rawType = "long"; readMethod = "TryReadInt64BigEndian"; return true;
            case "u64le": size = 8; rawType = "ulong"; readMethod = "TryReadUInt64LittleEndian"; return true;
            case "u64be": size = 8; rawType = "ulong"; readMethod = "TryReadUInt64BigEndian"; return true;
            case "f32le": size = 4; rawType = "float"; readMethod = "TryReadSingleLittleEndian"; return true;
            case "f32be": size = 4; rawType = "float"; readMethod = "TryReadSingleBigEndian"; return true;
            case "f64le": size = 8; rawType = "double"; readMethod = "TryReadDoubleLittleEndian"; return true;
            case "f64be": size = 8; rawType = "double"; readMethod = "TryReadDoubleBigEndian"; return true;
            case "bool8": size = 1; rawType = "bool"; readMethod = "TryReadBool8"; return true;
            default:
                size = 0;
                rawType = string.Empty;
                readMethod = string.Empty;
                return false;
        }
    }

    private static string ToCamelCase(string value) =>
        string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);
}
