using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class PacketDispatcherEmitter
{
    private const int MaximumStackPayloadSize = 4096;

    public static string Emit(IReadOnlyList<PacketDefinition> packets)
    {
        PacketDefinition[] dispatchable = packets
            .Where(FixedPacketCodecEmitter.CanEmit)
            .OrderBy(static packet => packet.Name, StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("using global::System.Buffers;");
        source.AppendLine();
        source.AppendLine("namespace Metin2.Protocol.Generated;");
        source.AppendLine();
        source.AppendLine("public enum PacketDispatchStatus : byte");
        source.AppendLine("{");
        source.AppendLine("    Done = 0,");
        source.AppendLine("    MalformedPayload = 1,");
        source.AppendLine("    UnsupportedCodec = 2,");
        source.AppendLine("    UnknownPacketId = 3");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public readonly record struct PacketDispatchAttempt(");
        source.AppendLine("    PacketDispatchStatus Status,");
        source.AppendLine("    global::System.Threading.Tasks.ValueTask HandlerCompletion)");
        source.AppendLine("{");
        source.AppendLine("    public bool IsDispatched => Status == PacketDispatchStatus.Done;");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public interface IPacketDispatchTarget");
        source.AppendLine("{");
        foreach (PacketDefinition packet in dispatchable)
        {
            source.AppendLine($"    global::System.Threading.Tasks.ValueTask HandleAsync(global::Metin2.Protocol.Generated.Packets.{packet.Name} packet, global::System.Threading.CancellationToken cancellationToken);");
        }
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public static class PacketDispatcher");
        source.AppendLine("{");
        source.AppendLine("    public static PacketDispatchAttempt Dispatch(");
        source.AppendLine("        in PacketRegistration registration,");
        source.AppendLine("        in global::System.Buffers.ReadOnlySequence<byte> payload,");
        source.AppendLine("        IPacketDispatchTarget target,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(target);");
        source.AppendLine();
        source.AppendLine("        return registration.Id switch");
        source.AppendLine("        {");
        foreach (PacketDefinition packet in dispatchable)
        {
            source.AppendLine($"            PacketId.{packet.Name} => Dispatch{packet.Name}(payload, target, cancellationToken),");
        }
        source.AppendLine("            0 => new PacketDispatchAttempt(PacketDispatchStatus.UnknownPacketId, default),");
        source.AppendLine("            _ => new PacketDispatchAttempt(PacketDispatchStatus.UnsupportedCodec, default)");
        source.AppendLine("        };");
        source.AppendLine("    }");

        foreach (PacketDefinition packet in dispatchable)
        {
            source.AppendLine();
            EmitPacketMethod(source, packet);
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitPacketMethod(StringBuilder source, PacketDefinition packet)
    {
        int payloadSize = GetPayloadSize(packet);
        source.AppendLine($"    private static PacketDispatchAttempt Dispatch{packet.Name}(");
        source.AppendLine("        in global::System.Buffers.ReadOnlySequence<byte> payload,");
        source.AppendLine("        IPacketDispatchTarget target,");
        source.AppendLine("        global::System.Threading.CancellationToken cancellationToken)");
        source.AppendLine("    {");
        source.AppendLine($"        if (payload.Length != global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.PayloadSize)");
        source.AppendLine("        {");
        source.AppendLine("            return new PacketDispatchAttempt(PacketDispatchStatus.MalformedPayload, default);");
        source.AppendLine("        }");
        source.AppendLine();

        if (payloadSize > MaximumStackPayloadSize)
        {
            source.AppendLine("        if (!payload.IsSingleSegment)");
            source.AppendLine("        {");
            source.AppendLine("            return new PacketDispatchAttempt(PacketDispatchStatus.UnsupportedCodec, default);");
            source.AppendLine("        }");
            source.AppendLine();
        }

        source.AppendLine($"        global::Metin2.Protocol.Generated.Packets.{packet.Name} packet;");
        source.AppendLine("        if (payload.IsSingleSegment)");
        source.AppendLine("        {");
        source.AppendLine("            var reader = new global::Metin2.Protocol.IO.PacketReader(payload.FirstSpan);");
        source.AppendLine($"            if (!global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.TryRead(ref reader, out packet) || reader.Remaining != 0)");
        source.AppendLine("            {");
        source.AppendLine("                return new PacketDispatchAttempt(PacketDispatchStatus.MalformedPayload, default);");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine("        else");
        source.AppendLine("        {");

        if (payloadSize <= MaximumStackPayloadSize)
        {
            source.AppendLine($"            global::System.Span<byte> scratch = stackalloc byte[global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.PayloadSize];");
            source.AppendLine("            payload.CopyTo(scratch);");
            source.AppendLine("            var reader = new global::Metin2.Protocol.IO.PacketReader(scratch);");
            source.AppendLine($"            if (!global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.TryRead(ref reader, out packet) || reader.Remaining != 0)");
            source.AppendLine("            {");
            source.AppendLine("                return new PacketDispatchAttempt(PacketDispatchStatus.MalformedPayload, default);");
            source.AppendLine("            }");
        }
        else
        {
            source.AppendLine("            return new PacketDispatchAttempt(PacketDispatchStatus.UnsupportedCodec, default);");
        }

        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return new PacketDispatchAttempt(");
        source.AppendLine("            PacketDispatchStatus.Done,");
        source.AppendLine("            target.HandleAsync(packet, cancellationToken));");
        source.AppendLine("    }");
    }

    private static int GetPayloadSize(PacketDefinition packet)
    {
        int size = 0;
        foreach (FieldDefinition field in packet.Fields)
        {
            if (TryGetScalarSize(field.Type, out int scalarSize))
            {
                size = checked(size + scalarSize);
                continue;
            }

            if (field.Type == "fixed_string")
            {
                size = checked(size + field.Length!.Value);
                continue;
            }

            if (field.Type == "array")
            {
                _ = TryGetScalarSize(field.Element!.Type, out int elementSize);
                size = checked(size + checked(field.Length!.Value * elementSize));
                continue;
            }

            throw new InvalidOperationException($"Packet '{packet.Name}' is not fixed-codec dispatchable.");
        }

        return size;
    }

    private static bool TryGetScalarSize(string type, out int size)
    {
        switch (type)
        {
            case "i8":
            case "u8":
            case "bool8": size = 1; return true;
            case "i16le":
            case "i16be":
            case "u16le":
            case "u16be": size = 2; return true;
            case "i32le":
            case "i32be":
            case "u32le":
            case "u32be":
            case "f32le":
            case "f32be": size = 4; return true;
            case "i64le":
            case "i64be":
            case "u64le":
            case "u64be":
            case "f64le":
            case "f64be": size = 8; return true;
            default: size = 0; return false;
        }
    }
}
