using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class PacketRegistryEmitter
{
    public static string Emit(IReadOnlyList<PacketDefinition> packets)
    {
        PacketDefinition[] ordered = packets.OrderBy(static packet => packet.Name, StringComparer.Ordinal).ToArray();
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("namespace Metin2.Protocol.Generated;");
        source.AppendLine();
        source.AppendLine("public enum PacketId : ushort");
        source.AppendLine("{");
        for (int i = 0; i < ordered.Length; i++)
        {
            source.AppendLine($"    {ordered[i].Name} = {i + 1},");
        }
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public readonly record struct PacketRegistration(");
        source.AppendLine("    PacketId Id,");
        source.AppendLine("    ushort Opcode,");
        source.AppendLine("    PacketDirection Direction,");
        source.AppendLine("    PacketPhase AllowedPhase,");
        source.AppendLine("    bool HasSequence,");
        source.AppendLine("    bool HasFixedPayloadSize,");
        source.AppendLine("    int PayloadSize);");
        source.AppendLine();
        source.AppendLine("public static class PacketRegistry");
        source.AppendLine("{");
        source.AppendLine("    public static bool TryGet(ushort opcode, PacketDirection direction, PacketPhase phase, out PacketRegistration registration)");
        source.AppendLine("    {");
        foreach (PacketDefinition packet in ordered.OrderBy(static packet => packet.Opcode).ThenBy(static packet => packet.Name, StringComparer.Ordinal))
        {
            bool hasFixedSize = TryGetPayloadSize(packet, out int payloadSize);
            source.AppendLine($"        if (opcode == {packet.Opcode} && DirectionMatches(direction, {MapDirection(packet.Direction)}) && PhaseMatches(phase, {MapPhase(packet.Phase)}))");
            source.AppendLine("        {");
            source.AppendLine($"            registration = new PacketRegistration(PacketId.{packet.Name}, {packet.Opcode}, {MapDirection(packet.Direction)}, {MapPhase(packet.Phase)}, {(packet.Sequence ? "true" : "false")}, {(hasFixedSize ? "true" : "false")}, {(hasFixedSize ? payloadSize : -1)});");
            source.AppendLine("            return true;");
            source.AppendLine("        }");
        }
        source.AppendLine();
        source.AppendLine("        registration = default;");
        source.AppendLine("        return false;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static bool DirectionMatches(PacketDirection actual, PacketDirection declared) =>");
        source.AppendLine("        declared == PacketDirection.Bidirectional || actual == declared;");
        source.AppendLine();
        source.AppendLine("    private static bool PhaseMatches(PacketPhase actual, PacketPhase declared) =>");
        source.AppendLine("        declared == PacketPhase.Any || actual == declared;");
        source.AppendLine("}");
        return source.ToString();
    }

    private static bool TryGetPayloadSize(PacketDefinition packet, out int payloadSize)
    {
        payloadSize = 0;
        if (packet.Size != "fixed") return false;

        try
        {
            foreach (FieldDefinition field in packet.Fields)
            {
                if (TryGetScalarSize(field.Type, out int scalarSize))
                {
                    payloadSize = checked(payloadSize + scalarSize);
                    continue;
                }

                if (field.Type == "fixed_string" && field.Length is > 0)
                {
                    payloadSize = checked(payloadSize + field.Length.Value);
                    continue;
                }

                if (field.Type == "array" && field.Length is > 0 && field.Element is not null && TryGetScalarSize(field.Element.Type, out int elementSize))
                {
                    payloadSize = checked(payloadSize + checked(field.Length.Value * elementSize));
                    continue;
                }

                return false;
            }

            return true;
        }
        catch (OverflowException)
        {
            payloadSize = 0;
            return false;
        }
    }

    private static bool TryGetScalarSize(string type, out int size)
    {
        switch (type)
        {
            case "i8":
            case "u8":
            case "bool8": size = 1; return true;
            case "i16le":
            case "i16be":
            case "u16le":
            case "u16be": size = 2; return true;
            case "i32le":
            case "i32be":
            case "u32le":
            case "u32be":
            case "f32le":
            case "f32be": size = 4; return true;
            case "i64le":
            case "i64be":
            case "u64le":
            case "u64be":
            case "f64le":
            case "f64be": size = 8; return true;
            default: size = 0; return false;
        }
    }

    private static string MapDirection(string direction) => direction switch
    {
        "client_to_server" => "PacketDirection.ClientToServer",
        "server_to_client" => "PacketDirection.ServerToClient",
        _ => "PacketDirection.Bidirectional"
    };

    private static string MapPhase(string phase) => phase switch
    {
        "handshake" => "PacketPhase.Handshake",
        "login" => "PacketPhase.Login",
        "auth" => "PacketPhase.Auth",
        "select" => "PacketPhase.Select",
        "loading" => "PacketPhase.Loading",
        "game" => "PacketPhase.Game",
        _ => "PacketPhase.Any"
    };
}
