using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class PacketModelEmitter
{
    private const string GeneratedNamespace = "Metin2.Protocol.Generated.Packets";

    public static string Emit(PacketDefinition packet)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();

        string declaration = BuildDeclaration(packet);
        source.AppendLine(declaration);
        source.AppendLine("{");
        source.AppendLine($"    public const ushort Opcode = {packet.Opcode};");
        source.AppendLine($"    public const global::Metin2.Protocol.Generated.PacketDirection Direction = {MapDirection(packet.Direction)};");
        source.AppendLine($"    public const global::Metin2.Protocol.Generated.PacketPhase Phase = {MapPhase(packet.Phase)};");
        source.AppendLine($"    public const bool HasSequence = {(packet.Sequence ? "true" : "false")};");
        source.AppendLine($"    public const int Since = {packet.Since};");
        source.AppendLine(packet.Until.HasValue
            ? $"    public static int? Until => {packet.Until.Value};"
            : "    public static int? Until => null;");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string BuildDeclaration(PacketDefinition packet)
    {
        if (packet.Fields.Count == 0)
        {
            return $"public readonly partial record struct {packet.Name}";
        }

        string parameters = string.Join(",\n    ", packet.Fields.Select(field =>
            $"{MapFieldType(field)} {ToPascalCase(field.Name)}"));

        return $"public readonly partial record struct {packet.Name}(\n    {parameters})";
    }

    private static string MapFieldType(FieldDefinition field)
    {
        if (!string.IsNullOrWhiteSpace(field.DomainType))
        {
            return MapDomainType(field.DomainType!);
        }

        return field.Type switch
        {
            "i8" => "sbyte",
            "u8" => "byte",
            "i16le" or "i16be" => "short",
            "u16le" or "u16be" => "ushort",
            "i32le" or "i32be" => "int",
            "u32le" or "u32be" => "uint",
            "i64le" or "i64be" => "long",
            "u64le" or "u64be" => "ulong",
            "f32le" or "f32be" => "float",
            "f64le" or "f64be" => "double",
            "bool8" => "bool",
            "fixed_string" or "string" => "string",
            "bytes" => "global::System.ReadOnlyMemory<byte>",
            _ => "global::System.ReadOnlyMemory<byte>"
        };
    }

    private static string MapDomainType(string domainType)
    {
        return domainType switch
        {
            "AccountId" => "global::Metin2.Shared.Identity.AccountId",
            "CharacterId" => "global::Metin2.Shared.Identity.CharacterId",
            "ItemId" => "global::Metin2.Shared.Identity.ItemId",
            "GuildId" => "global::Metin2.Shared.Identity.GuildId",
            "MapId" => "global::Metin2.Shared.Identity.MapId",
            "EntityId" => "global::Metin2.Shared.Identity.EntityId",
            "MonsterId" => "global::Metin2.Shared.Identity.MonsterId",
            _ => domainType
        };
    }

    private static string MapDirection(string direction)
    {
        return direction switch
        {
            "client_to_server" => "global::Metin2.Protocol.Generated.PacketDirection.ClientToServer",
            "server_to_client" => "global::Metin2.Protocol.Generated.PacketDirection.ServerToClient",
            "bidirectional" => "global::Metin2.Protocol.Generated.PacketDirection.Bidirectional",
            _ => "global::Metin2.Protocol.Generated.PacketDirection.Bidirectional"
        };
    }

    private static string MapPhase(string phase)
    {
        return phase switch
        {
            "handshake" => "global::Metin2.Protocol.Generated.PacketPhase.Handshake",
            "login" => "global::Metin2.Protocol.Generated.PacketPhase.Login",
            "auth" => "global::Metin2.Protocol.Generated.PacketPhase.Auth",
            "select" => "global::Metin2.Protocol.Generated.PacketPhase.Select",
            "loading" => "global::Metin2.Protocol.Generated.PacketPhase.Loading",
            "game" => "global::Metin2.Protocol.Generated.PacketPhase.Game",
            "any" => "global::Metin2.Protocol.Generated.PacketPhase.Any",
            _ => "global::Metin2.Protocol.Generated.PacketPhase.Any"
        };
    }

    internal static string ToPascalCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        var builder = new StringBuilder(value.Length);
        bool uppercaseNext = true;

        foreach (char character in value)
        {
            if (character is '_' or '-' or ' ')
            {
                uppercaseNext = true;
                continue;
            }

            builder.Append(uppercaseNext ? char.ToUpperInvariant(character) : character);
            uppercaseNext = false;
        }

        return builder.ToString();
    }
}
