using System.Text;
using Metin2.Protocol.Generator.Model;

namespace Metin2.Protocol.Generator.Generation;

internal static class PacketFrameWriterEmitter
{
    public static string Emit(IReadOnlyList<PacketDefinition> packets)
    {
        PacketDefinition[] writable = packets
            .Where(FixedPacketCodecEmitter.CanEmit)
            .OrderBy(static packet => packet.Name, StringComparer.Ordinal)
            .ToArray();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("namespace Metin2.Protocol.Generated;");
        source.AppendLine();
        source.AppendLine("public enum PacketFrameWriteStatus : byte");
        source.AppendLine("{");
        source.AppendLine("    Done = 0,");
        source.AppendLine("    InvalidPacket = 1,");
        source.AppendLine("    InsufficientDestination = 2");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public static class PacketFrameWriter");
        source.AppendLine("{");

        foreach (PacketDefinition packet in writable)
        {
            EmitPacketWriter(source, packet);
        }

        source.AppendLine("}");
        return source.ToString();
    }

    private static void EmitPacketWriter(StringBuilder source, PacketDefinition packet)
    {
        string sequenceParameter = packet.Sequence ? ", byte sequence" : string.Empty;
        int sequenceSize = packet.Sequence ? 1 : 0;

        source.AppendLine($"    public static PacketFrameWriteStatus TryWrite(in global::Metin2.Protocol.Generated.Packets.{packet.Name} packet{sequenceParameter}, global::System.Span<byte> destination, out int written)");
        source.AppendLine("    {");
        source.AppendLine("        written = 0;");
        source.AppendLine($"        const int frameSize = 1 + global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.PayloadSize + {sequenceSize};");
        source.AppendLine("        if (destination.Length < frameSize)");
        source.AppendLine("        {");
        source.AppendLine("            return PacketFrameWriteStatus.InsufficientDestination;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine($"        var payloadWriter = new global::Metin2.Protocol.IO.PacketWriter(destination.Slice(1, global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.PayloadSize));");
        source.AppendLine($"        if (!global::Metin2.Protocol.Generated.Packets.{packet.Name}Codec.TryWrite(ref payloadWriter, in packet) || payloadWriter.Remaining != 0)");
        source.AppendLine("        {");
        source.AppendLine("            return PacketFrameWriteStatus.InvalidPacket;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine($"        destination[0] = 0x{packet.Opcode:X2};");
        if (packet.Sequence)
        {
            source.AppendLine("        destination[frameSize - 1] = sequence;");
        }
        source.AppendLine("        written = frameSize;");
        source.AppendLine("        return PacketFrameWriteStatus.Done;");
        source.AppendLine("    }");
        source.AppendLine();
    }
}
